# Generated by Django 3.2.4 on 2021-07-01 17:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5b1b0428-de8c-433a-9275-4c24aa46a114'), help_text='Id única para este livro em toda a biblioteca', primary_key=True, serialize=False),
        ),
    ]
